version: "3"
services: 
  server:
    build: .
    volumes: 
      - ./:/app
    ports:
      - 3000:3000
  mongo:
    image: mongo
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081